export const Events = {
  PLAYER_CLIP_LOADED: 'PLAYER_CLIP_LOADED',
  PLAYER_QUEUE_ENDED: 'PLAYER_QUEUE_ENDED',
  PLAYER_RESUME_AFTER_CLIP_HAS_ENDED: 'PLAYER_RESUME_AFTER_CLIP_HAS_ENDED',
  PLAYER_STATE_CHANGED: 'PLAYER_STATE_CHANGED'
}
