export const Events = {
  PLAYER_CANNOT_STREAM_WITHOUT_WIFI: 'PLAYER_CANNOT_STREAM_WITHOUT_WIFI',
  PLAYER_CLIP_LOADED: 'PLAYER_CLIP_LOADED',
  PLAYER_QUEUE_ENDED: 'PLAYER_QUEUE_ENDED',
  PLAYER_REMOTE_DUCK: 'PLAYER_REMOTE_DUCK',
  PLAYER_REMOTE_JUMP_BACKWARD: 'PLAYER_REMOTE_JUMP_BACKWARD',
  PLAYER_REMOTE_JUMP_FORWARD: 'PLAYER_REMOTE_JUMP_FORWARD',
  PLAYER_REMOTE_NEXT: 'PLAYER_REMOTE_NEXT',
  PLAYER_REMOTE_PAUSE: 'PLAYER_REMOTE_PAUSE',
  PLAYER_REMOTE_PLAY: 'PLAYER_REMOTE_PLAY',
  PLAYER_REMOTE_PREVIOUS: 'PLAYER_REMOTE_PREVIOUS',
  PLAYER_REMOTE_SEEK: 'PLAYER_REMOTE_SEEK',
  PLAYER_REMOTE_STOP: 'PLAYER_REMOTE_STOP',
  PLAYER_RESUME_AFTER_CLIP_HAS_ENDED: 'PLAYER_RESUME_AFTER_CLIP_HAS_ENDED',
  PLAYER_STATE_CHANGED: 'PLAYER_STATE_CHANGED'
}
