import { IFilters } from './Interfaces'

export const Filters: IFilters = {
  _subscribedKey: 'subscribed',
  _downloadedKey: 'downloaded',
  _allPodcastsKey: 'allPodcasts',
  _categoryKey: 'category',
  _alphabeticalKey: 'alphabetical',
  _mostRecentKey: 'most-recent',
  _randomKey: 'random',
  _topPastDay: 'top-past-day',
  _topPastWeek: 'top-past-week',
  _topPastMonth: 'top-past-month',
  _topPastYear: 'top-past-year',
  _chronologicalKey: 'chronological',
  _oldestKey: 'oldest',
  _myClipsKey: 'clips',
  _allEpisodesKey: 'allEpisodes',
  _podcastsKey: 'podcasts',
  _episodesKey: 'episodes',
  _clipsKey: 'clips',
  _playlistKey: 'playlist',
  _aboutKey: 'about',
  _showNotesKey: 'showNotes',
  _titleKey: 'title',
  _myPlaylistsKey: 'myPlaylists',
  _fromThisPodcast: 'fromThisPodcast',
  _fromThisEpisode: 'fromThisEpisode',
  _allCategories: 'allCategories'
}
