export const Keys = {
  APP_HAS_LAUNCHED: 'APP_HAS_LAUNCHED',
  BEARER_TOKEN: 'BEARER_TOKEN',
  HISTORY_ITEMS: 'HISTORY_ITEMS',
  NOW_PLAYING_ITEM: 'NOW_PLAYING_ITEM',
  QUEUE_ITEMS: 'QUEUE_ITEMS',
  SUBSCRIBED_PLAYLIST_IDS: 'SUBSCRIBED_PLAYLIST_IDS',
  SUBSCRIBED_PODCAST_IDS: 'SUBSCRIBED_PODCAST_IDS',
  SUBSCRIBED_USER_IDS: 'SUBSCRIBED_USER_IDS'
}
