export const RouteNames = {
  AuthNavigator: 'AuthNavigator',
  AuthScreen: 'AuthScreen',
  ClipsScreen: 'ClipsScreen',
  DownloadsScreen: 'DownloadsListScreen',
  EpisodeScreen: 'EpisodeScreen',
  EpisodesScreen: 'EpisodesScreen',
  FindScreen: 'FindScreen',
  FindSearchScreen: 'FindSearchScreen',
  MainApp: 'MainApp',
  MoreScreen: 'MoreScreen',
  MyProfileScreen: 'MyProfileScreen',
  Onboarding: 'Onboarding',
  OnboardingScreen: 'OnboardingScreen',
  PlaylistScreen: 'PlaylistScreen',
  PlaylistsScreen: 'PlaylistsScreen',
  PodcastScreen: 'PodcastScreen',
  PodcastsScreen: 'PodcastsScreen',
  ProfilesScreen: 'ProfilesScreen',
  ProfileScreen: 'ProfileScreen',
  SettingsScreen: 'SettingsScreen',
  TabNavigator: 'TabNavigator'
}
